import { Component, OnInit, AfterViewInit, ViewChild, ContentChild } from '@angular/core';
import { Observable, Subject } from 'rxjs';
import { PersonalizeMenuComponent } from '../personalize-menu/personalize-menu.component';
import { PersonalizeGridComponent } from '../personalize-grid/personalize-grid.component';
import { SohoDataGridComponent, ArgumentHelper } from 'ids-enterprise-ng';
import { AssertNotNull } from '@angular/compiler';

@Component({
  selector: 'app-datagrid',
  templateUrl: './datagrid.component.html',
  styleUrls: ['./datagrid.component.css']
})
export class DatagridComponent implements OnInit, AfterViewInit {

  @ViewChild(PersonalizeGridComponent)
  public readonly personalizeMenu: PersonalizeGridComponent;

  @ViewChild(SohoDataGridComponent)
  public readonly userGrid: SohoDataGridComponent;

  public columns: SohoDataGridColumn[] = [
    {
      id: 'selectionCheckbox',
      sortable: false,
      resizable: false,
      width: 50,
      formatter: Soho.Formatters.SelectionCheckbox,
      align: 'center',
      exportable: false
    },
    {
      id: 'name',
      name: Soho.Locale.translate('UserName'),
      field: 'name',
      sortable: true,
      filterType: 'text',
      click: (e: Event, data: SohoDataGridColumnClickData[]) => {
        e.preventDefault();
        e.stopImmediatePropagation();
      },
      formatter: Soho.Formatters.Hyperlink,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'title',
      name: Soho.Locale.translate('UserTitle'),
      field: 'title',
      sortable: true,
      filterType: 'text',
      width: 150,
      formatter: Soho.Formatters.Text,
      hidden: true,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'email',
      name: Soho.Locale.translate('UserEmail'),
      field: 'email',
      sortable: true,
      filterType: 'text',
      width: 150,
      formatter: Soho.Formatters.Text,
      hidden: false,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'groupName',
      name: Soho.Locale.translate('UserGroups'),
      field: 'groups',
      sortable: true,
      filterType: 'text',
      width: 400,
      formatter: (row: number, cell: any, value: any[], column: SohoDataGridColumn, item: any, api: SohoDataGridStatic): any => {
        let groupName = '';
        if (value) {
          value.sort((a, b) => (a.groupName > b.groupName) ? 1 : -1);
          value.forEach(
            (group: any) => {
              if (group.parent == null) {
                const subGroups = value.filter((g) => g.parent === group.id);
                if (subGroups.length === 0) {
                  groupName += group.groupName + ', ';
                } else {
                  groupName += group.groupName + ' (';
                  subGroups.forEach((subGroup: any) => {
                    groupName += subGroup.groupName + ', ';
                  });
                  groupName = groupName.substring(0, groupName.length - 2) + '), ';
                }
              }
            });

          if (groupName.length > 1) {
            groupName = groupName.substring(0, groupName.length - 2);
          }
        }

        return groupName;
      },
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'fullName',
      name: Soho.Locale.translate('UserFullName'),
      field: 'fullName',
      sortable: true,
      filterType: 'text',
      width: 160,
      formatter: Soho.Formatters.Text,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'operatorCode',
      name: Soho.Locale.translate('UserOperatorCode'),
      field: 'operatorCode',
      sortable: true,
      filterType: 'text',
      width: 140,
      hidden: true,
      formatter: Soho.Formatters.Text,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'defaultBusinessUnit',
      name: Soho.Locale.translate('UserDefaultBusinessUnit'),
      sortable: true,
      filterType: 'text',
      width: 180,
      field: 'defaultBusinessUnit',
      formatter: Soho.Formatters.Text,
      hidden: true,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'defaultLedger',
      name: Soho.Locale.translate('UserDefaultLedger'),
      field: 'defaultLedger',
      sortable: true,
      filterType: 'text',
      width: 130,
      formatter: Soho.Formatters.Text,
      hidden: true,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'lastLogonDateTime',
      name: Soho.Locale.translate('UserLastLogonDate'),
      field: 'lastLogonDateTime',
      sortable: true,
      filterType: 'date',
      formatter: (row: number, cell: any, value: any, column: SohoDataGridColumn, item: any, api: SohoDataGridStatic): any => {
        value = value ? value : item.createdDateTime;
        return Soho.Formatters.Date(row, cell, value, column, item, api);
      },
      dateFormat: Soho.Locale.calendar().dateFormat.datetime,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'lockStatus',
      name: Soho.Locale.translate('UserLockStatus'),
      field: 'locked',
      filterType: 'checkbox',
      width: 90,
      sortable: true,
      formatter: (row: number, cell: any, value: any, column: SohoDataGridColumn, item: any, api: SohoDataGridStatic): any => {
        if (value == null || value === 'Unlocked') {
          value = false;
        } else {
          value = true;
        }
        return Soho.Formatters.Checkbox(row, cell, value, column, item, api);
      },
      hidden: true,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'deleted',
      name: Soho.Locale.translate('UserDeleted'),
      field: 'deleted',
      width: 90,
      sortable: true,
      filterType: 'checkbox',
      formatter: Soho.Formatters.Checkbox,
      hidden: true,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'description',
      name: Soho.Locale.translate('UserDescription'),
      field: 'description',
      sortable: true,
      filterType: 'text',
      width: 250,
      formatter: Soho.Formatters.Text,
      hidden: true,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'lookupCode',
      name: Soho.Locale.translate('UserLookupCode'),
      field: 'lookupCode',
      sortable: true,
      filterType: 'text',
      width: 180,
      formatter: Soho.Formatters.Text,
      hidden: true,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'shortHeading',
      name: Soho.Locale.translate('UserShortHeading'),
      field: 'shortHeading',
      sortable: true,
      filterType: 'text',
      width: 230,
      formatter: Soho.Formatters.Text,
      hidden: true,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'language',
      name: Soho.Locale.translate('UserLanguage'),
      field: 'language',
      sortable: true,
      filterType: 'text',
      width: 120,
      formatter: (row: number, cell: any, value: any, column: SohoDataGridColumn): string => {
        // const language = this.store.selectSnapshot(UserFormState.languages).find((l) => l.value === value);
        // return language ? language.label : '';
        return value;
      },
      hidden: true,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'setOperatingSystemDate',
      name: Soho.Locale.translate('UserSetOperatingSystemDate'),
      field: 'setOperatingSystemDate',
      sortable: true,
      filterType: 'text',
      width: 210,
      formatter: Soho.Formatters.Text,
      hidden: true,
      reorderable: true,
      textOverflow: 'ellipsis'
    },
    {
      id: 'status',
      name: Soho.Locale.translate('UserStatus'),
      field: 'status',
      sortable: true,
      filterType: 'text',
      width: 120,
      formatter: Soho.Formatters.Text,
      hidden: true,
      reorderable: true,
      textOverflow: 'ellipsis'
    }
  ];

  public users = [{
          id: '195e67c8-6263-43d9-af4b-3bc355f4e1e6',
          'name': 'admin',
          'fullName': 'System Administrator',
          'description': 'Member of the SunSystems Administrator Group set during installation of SunSystems',
          'title': null,
          'preferredLocale': 'en-GB',
          'email': null,
          'locked': 'Unlocked',
          'lastLogonDateTime': '2020-01-20T10:46:29.183Z',
          'userPhoto': null,
          'operatorCode': null,
          'status': 'Open',
          'lookupCode': null,
          'shortHeading': null,
          'defaultBusinessUnit': null,
          'defaultLedger': null,
          'language': null,
          'setOperatingSystemDate': 'ForceEntry',
          'dateSource': 'DateFromServer',
          'hijriCalendar': false,
          'groups': [
            {
              'status': null,
              'id': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'groupName': 'Reporting',
              'description': 'Members are permitted to use SunSystems Reporting',
              'isChecked': false,
              'parent': null,
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': false,
              'depth': 0,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': true
            },
            {
              'status': null,
              'id': '643f0212-e61f-11e1-985c-5a316288709b',
              'groupName': 'Configuration Administrators',
              'description': 'Members can amend SunSystems settings using Configuration Manager',
              'isChecked': false,
              'parent': null,
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 0,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': '73e2b729-4d1d-495f-8cd2-914a2618c1d7',
              'groupName': 'Reporting Administrators',
              'description': 'Members can administer Reporting',
              'isChecked': false,
              'parent': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': '93d5d4f9-2c5d-41d3-a4f4-c8a2e71db72f',
              'groupName': 'Reporting Model Managers',
              'description': 'Members can synchronize and manage Report Models',
              'isChecked': false,
              'parent': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': 'c460d47a-7c59-4b7e-9363-cf8bb06027c8',
              'groupName': 'Security Administrators',
              'description': 'Administrators of SunSystems User Accounts, Groups and Security Policy',
              'isChecked': false,
              'parent': null,
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 0,
              'expanded': false,
              'singleChild': true,
              'deleted': false,
              'canParent': true
            }
          ],
          'deleted': false,
          'createdDateTime': '2020-01-07T09:03:41.627Z',
          'standardAuthentication': true,
          'password': null,
          'userMustChangePasswordAtNextLogin': false,
          'sunSystemsAuthorization': false,
          'authorizationPassword': null,
          'invalidAuthorizationCount': 0,
          'singleSignOn': false,
          'windowsAccount': null,
          'upn': null,
          'directoryServiceAuthentication': false,
          'directoryServiceAccount': null,
          'windowsAuthentication': false,
          'windowsSid': null,
          'windowsEnableWorkflowApproval': false
        },
        {
          'id': '25c824ae-28c3-4779-8b0b-4b4f8777fe00',
          'name': 'PK1',
          'fullName': 'Mr PK1',
          'description': 'PK1 Menu User 1',
          'title': null,
          'preferredLocale': 'en-GB',
          'email': null,
          'locked': 'Unlocked',
          'lastLogonDateTime': '2020-01-09T16:05:44.463Z',
          'userPhoto': null,
          'operatorCode': 'PK1',
          'status': 'Open',
          'lookupCode': 'PK1            ',
          'shortHeading': 'PK1 Menu User 1',
          'defaultBusinessUnit': 'PK1',
          'defaultLedger': 'A',
          'language': '1',
          'setOperatingSystemDate': 'ConfirmAtLogin',
          'dateSource': 'DateFromServer',
          'hijriCalendar': false,
          'groups': [
            {
              'status': null,
              'id': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'groupName': 'Reporting',
              'description': 'Members are permitted to use SunSystems Reporting',
              'isChecked': false,
              'parent': null,
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': false,
              'depth': 0,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': true
            },
            {
              'status': null,
              'id': '4b9e9cf7-0d8d-4d8c-b2b8-2c976dc2d4bb',
              'groupName': 'Reporting Designers',
              'description': 'Members can author reports using Report Designer',
              'isChecked': false,
              'parent': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': '142eec4e-1875-4422-a71a-2d986d68b3ae',
              'groupName': 'PK1',
              'description': 'PK1 Financials Group',
              'isChecked': false,
              'parent': 'f4c31f9b-806b-4156-878e-ed45f11aa5c1',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': 'bbe0a97f-6af3-49ab-808a-8198f112ef74',
              'groupName': 'Reporting Publishers',
              'description': 'Members can access and store reports in the report store',
              'isChecked': false,
              'parent': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': '2a590555-df39-4187-be63-84a8537bd08e',
              'groupName': 'Reporting Schedulers',
              'description': 'Members can schedule reports',
              'isChecked': false,
              'parent': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': 'f4c31f9b-806b-4156-878e-ed45f11aa5c1',
              'groupName': 'SunSystems Users',
              'description': 'SunSystems Users',
              'isChecked': false,
              'parent': null,
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': false,
              'depth': 0,
              'expanded': false,
              'singleChild': true,
              'deleted': false,
              'canParent': true
            }
          ],
          'deleted': false,
          'createdDateTime': '2020-01-07T09:03:59.923Z',
          'standardAuthentication': true,
          'password': null,
          'userMustChangePasswordAtNextLogin': false,
          'sunSystemsAuthorization': false,
          'authorizationPassword': null,
          'invalidAuthorizationCount': 0,
          'singleSignOn': false,
          'windowsAccount': null,
          'upn': null,
          'directoryServiceAuthentication': false,
          'directoryServiceAccount': null,
          'windowsAuthentication': false,
          'windowsSid': null,
          'windowsEnableWorkflowApproval': false
        },
        {
          'id': '67eaec29-6a81-41e0-ae3d-04f0cece3f6c',
          'name': 'PK2',
          'fullName': 'Ms PK2',
          'description': 'PK1 Menu User 2',
          'title': null,
          'preferredLocale': 'en-GB',
          'email': null,
          'locked': 'Unlocked',
          'lastLogonDateTime': '2013-10-15T10:12:41Z',
          'userPhoto': null,
          'operatorCode': 'PK2',
          'status': 'Open',
          'lookupCode': 'PK2            ',
          'shortHeading': 'PK1 Menu User 2',
          'defaultBusinessUnit': 'PK1',
          'defaultLedger': 'A',
          'language': '1',
          'setOperatingSystemDate': 'ConfirmAtLogin',
          'dateSource': 'DateFromServer',
          'hijriCalendar': false,
          'groups': [
            {
              'status': null,
              'id': '9c76f780-2603-4aef-984f-aec6e410a419',
              'groupName': 'PK2',
              'description': 'PK2 Order Fulfillment Group',
              'isChecked': false,
              'parent': 'f4c31f9b-806b-4156-878e-ed45f11aa5c1',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': 'f4c31f9b-806b-4156-878e-ed45f11aa5c1',
              'groupName': 'SunSystems Users',
              'description': 'SunSystems Users',
              'isChecked': false,
              'parent': null,
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': false,
              'depth': 0,
              'expanded': false,
              'singleChild': true,
              'deleted': false,
              'canParent': true
            }
          ],
          'deleted': false,
          'createdDateTime': '2020-01-07T09:04:00.073Z',
          'standardAuthentication': true,
          'password': null,
          'userMustChangePasswordAtNextLogin': true,
          'sunSystemsAuthorization': false,
          'authorizationPassword': null,
          'invalidAuthorizationCount': 0,
          'singleSignOn': false,
          'windowsAccount': null,
          'upn': null,
          'directoryServiceAuthentication': false,
          'directoryServiceAccount': null,
          'windowsAuthentication': false,
          'windowsSid': null,
          'windowsEnableWorkflowApproval': false
        },
        {
          'id': '6ba162a9-4704-435b-9763-a5898413385c',
          'name': 'PK3',
          'fullName': 'PK3',
          'description': 'PK3',
          'title': null,
          'preferredLocale': 'en-GB',
          'email': null,
          'locked': 'Unlocked',
          'lastLogonDateTime': '2013-10-15T10:12:41Z',
          'userPhoto': null,
          'operatorCode': 'PK3',
          'status': 'Open',
          'lookupCode': 'PK3            ',
          'shortHeading': 'PK3            ',
          'defaultBusinessUnit': 'PK1',
          'defaultLedger': 'A',
          'language': '1',
          'setOperatingSystemDate': 'ConfirmAtLogin',
          'dateSource': 'DateFromServer',
          'hijriCalendar': false,
          'groups': [
            {
              'status': null,
              'id': '142eec4e-1875-4422-a71a-2d986d68b3ae',
              'groupName': 'PK1',
              'description': 'PK1 Financials Group',
              'isChecked': false,
              'parent': 'f4c31f9b-806b-4156-878e-ed45f11aa5c1',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': 'f4c31f9b-806b-4156-878e-ed45f11aa5c1',
              'groupName': 'SunSystems Users',
              'description': 'SunSystems Users',
              'isChecked': false,
              'parent': null,
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': false,
              'depth': 0,
              'expanded': false,
              'singleChild': true,
              'deleted': false,
              'canParent': true
            }
          ],
          'deleted': false,
          'createdDateTime': '2020-01-07T09:04:00.227Z',
          'standardAuthentication': true,
          'password': null,
          'userMustChangePasswordAtNextLogin': true,
          'sunSystemsAuthorization': false,
          'authorizationPassword': null,
          'invalidAuthorizationCount': 0,
          'singleSignOn': false,
          'windowsAccount': null,
          'upn': null,
          'directoryServiceAuthentication': false,
          'directoryServiceAccount': null,
          'windowsAuthentication': false,
          'windowsSid': null,
          'windowsEnableWorkflowApproval': false
        },
        {
          'id': 'fd4ecaf9-46fa-4cfc-8ead-f9c73f95ca16',
          'name': 'ZZZ',
          'fullName': 'System',
          'description': 'System',
          'title': null,
          'preferredLocale': 'en-GB',
          'email': null,
          'locked': 'Unlocked',
          'lastLogonDateTime': '2020-01-17T17:24:30.307Z',
          'userPhoto': null,
          'operatorCode': 'ZZZ',
          'status': 'Open',
          'lookupCode': 'ZZZ            ',
          'shortHeading': 'System',
          'defaultBusinessUnit': 'PK1',
          'defaultLedger': 'A',
          'language': '1',
          'setOperatingSystemDate': 'ConfirmAtLogin',
          'dateSource': 'DateFromServer',
          'hijriCalendar': false,
          'groups': [
            {
              'status': null,
              'id': 'b75a918c-f13f-4b54-865f-0cd20f052b0f',
              'groupName': 'SunSystems Connect',
              'description': 'SunSystems Connect',
              'isChecked': false,
              'parent': null,
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': false,
              'depth': 0,
              'expanded': false,
              'singleChild': true,
              'deleted': false,
              'canParent': true
            },
            {
              'status': null,
              'id': 'd84969b8-2bf8-4751-842b-0db960e99a19',
              'groupName': 'ZZZZZ',
              'description': 'System',
              'isChecked': false,
              'parent': 'f4c31f9b-806b-4156-878e-ed45f11aa5c1',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'groupName': 'Reporting',
              'description': 'Members are permitted to use SunSystems Reporting',
              'isChecked': false,
              'parent': null,
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': false,
              'depth': 0,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': true
            },
            {
              'status': null,
              'id': '4b9e9cf7-0d8d-4d8c-b2b8-2c976dc2d4bb',
              'groupName': 'Reporting Designers',
              'description': 'Members can author reports using Report Designer',
              'isChecked': false,
              'parent': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': 'fbc1b19a-3dd6-4481-b6dc-39802e0aa012',
              'groupName': 'Administrators',
              'description': 'SunSystems Connect Administrators',
              'isChecked': false,
              'parent': 'b75a918c-f13f-4b54-865f-0cd20f052b0f',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': 'bbe0a97f-6af3-49ab-808a-8198f112ef74',
              'groupName': 'Reporting Publishers',
              'description': 'Members can access and store reports in the report store',
              'isChecked': false,
              'parent': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': '2a590555-df39-4187-be63-84a8537bd08e',
              'groupName': 'Reporting Schedulers',
              'description': 'Members can schedule reports',
              'isChecked': false,
              'parent': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': '73e2b729-4d1d-495f-8cd2-914a2618c1d7',
              'groupName': 'Reporting Administrators',
              'description': 'Members can administer Reporting',
              'isChecked': false,
              'parent': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': '93d5d4f9-2c5d-41d3-a4f4-c8a2e71db72f',
              'groupName': 'Reporting Model Managers',
              'description': 'Members can synchronize and manage Report Models',
              'isChecked': false,
              'parent': 'a48f62a0-c540-468a-b452-241ba3cfbe6b',
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': true,
              'depth': 1,
              'expanded': false,
              'singleChild': false,
              'deleted': false,
              'canParent': false
            },
            {
              'status': null,
              'id': 'f4c31f9b-806b-4156-878e-ed45f11aa5c1',
              'groupName': 'SunSystems Users',
              'description': 'SunSystems Users',
              'isChecked': false,
              'parent': null,
              'children': null,
              'operatorGroupCode': null,
              'lookupCode': null,
              'shortHeading': null,
              'defaultBusinessUnit': null,
              'setOperationSystemDate': null,
              'defaultLedger': null,
              'joinable': false,
              'depth': 0,
              'expanded': false,
              'singleChild': true,
              'deleted': false,
              'canParent': true
            }
          ],
          'deleted': false,
          'createdDateTime': '2020-01-07T09:04:00.39Z',
          'standardAuthentication': true,
          'password': null,
          'userMustChangePasswordAtNextLogin': false,
          'sunSystemsAuthorization': false,
          'authorizationPassword': null,
          'invalidAuthorizationCount': 0,
          'singleSignOn': false,
          'windowsAccount': null,
          'upn': null,
          'directoryServiceAuthentication': false,
          'directoryServiceAccount': null,
          'windowsAuthentication': false,
          'windowsSid': null,
          'windowsEnableWorkflowApproval': false
        }
      ];

  public subject = new Subject<any[]>();
  public response$ = this.subject.asObservable();

  constructor() { }

  ngOnInit(): void {
  }

  ngAfterViewInit() {
    ArgumentHelper.checkNotNull('userGrid', this.userGrid);

    this.personalizeMenu.dataGrid = this.userGrid;

    setTimeout(() => {
      this.subject.next(this.users);
    }, 5000);
  }

  /**
   * Callback hander for the associated menu.
   *
   * Due to the way the toolbar's work, this method has to be invoked manuallt
   * from the toolbar component.
   *
   * @param event the event (needs typing!)
   */
  public onSelectedToolbar(event: any) {
  }

}
